/***********************************************************************************************
 * @file: generated_config_P20.c
 *
 * @description: This file is auto-generated from Excel configuration using a Python script.
 *               It defines the pin initialization array for SELECT_PLATFORM_PINS.
 *
 * @note: DO NOT EDIT THIS FILE MANUALLY.
 ***********************************************************************************************/

#include "pins_driver.h"

const pin_settings_config_t g_pin_mux_InitConfigArr[SELECT_PLATFORM_PINS] =
{
	/* pin1 */
	/* 预驱1 PWM1输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT1,
		.initValue = 0u,
	},

	/* pin2 */
	/* 预驱1 PWM2输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_3,
		.m_PinNum = GPIO_Pin_Num_3,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT1,
		.initValue = 0u,
	},

	/* pin3 */
	/* 预驱1 PWM3输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_4,
		.m_PinNum = GPIO_Pin_Num_4,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT1,
		.initValue = 0u,
	},

	/* pin4 */
	/* 预驱1 PWM4输出-先EN功能 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_5,
		.m_PinNum = GPIO_Pin_Num_5,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin5 */
	/* 记忆调节开关（预留）（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin6 */
	/* 主驾通风反馈-高低检 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_7,
		.m_PinNum = GPIO_Pin_Num_7,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin7 */
	/* 副驾通风反馈 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin8 */
	/* 通风3反馈 */
	{
		.pinEnable     = FALSE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin9 */
	/* 通风4反馈 */
	{
		.pinEnable     = FALSE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_9,
		.m_PinNum = GPIO_Pin_Num_9,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin15 */
	/* 晶振频率为16MHz */
	{
		.pinEnable     = FALSE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_11,
		.m_PinNum = GPIO_Pin_Num_11,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin16 */
	/* 晶振频率为16MHz */
	{
		.pinEnable     = FALSE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin17 */
	/* 预驱2 PWM1输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_3,
		.m_PinNum = GPIO_Pin_Num_3,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin18 */
	/* 预驱2 PWM2输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_4,
		.m_PinNum = GPIO_Pin_Num_4,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin19 */
	/* 预驱2 PWM3输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_12,
		.m_PinNum = GPIO_Pin_Num_12,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin20 */
	/* 预驱2 SPI SS2使能 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_13,
		.m_PinNum = GPIO_Pin_Num_13,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 1u,
	},

	/* pin21 */
	/* 预驱1 SPI MISO */
	{
		.pinEnable     = TRUE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_1,
		.m_PinNum = GPIO_Pin_Num_1,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT9,
		.initValue = 0u,
	},

	/* pin22 */
	/* 预驱1 SPI SCLK */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_14,
		.m_PinNum = GPIO_Pin_Num_14,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT9,
		.initValue = 0u,
	},

	/* pin23 */
	/* 分立12V使能控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_15,
		.m_PinNum = GPIO_Pin_Num_15,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 1u,
	},

	/* pin24 */
	/* LIN */
	{
		.pinEnable     = TRUE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT3,
		.initValue = 0u,
	},

	/* pin25 */
	/* LIN */
	{
		.pinEnable     = TRUE,
		.base = GPIOH_SFR,
		.m_Pin = GPIO_PIN_MASK_14,
		.m_PinNum = GPIO_Pin_Num_14,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT3,
		.initValue = 0u,
	},

	/* pin26 */
	/* LIN使能 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 1u,
	},

	/* pin27 */
	/* 预驱1 SPI SS1使能 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_1,
		.m_PinNum = GPIO_Pin_Num_1,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 1u,
	},

	/* pin28 */
	/* 预驱1 SPI MOSI */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT4,
		.initValue = 0u,
	},

	/* pin29 */
	/* CAN6 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_3,
		.m_PinNum = GPIO_Pin_Num_3,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT6,
		.initValue = 0u,
	},

	/* pin30 */
	/* CAN6 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_7,
		.m_PinNum = GPIO_Pin_Num_7,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT6,
		.initValue = 0u,
	},

	/* pin31 */
	/* 串口打印 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_OD,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT3,
		.initValue = 0u,
	},

	/* pin32 */
	/* CAN错误指示输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_9,
		.m_PinNum = GPIO_Pin_Num_9,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin33 */
	/* 喂狗信号 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_10,
		.m_PinNum = GPIO_Pin_Num_10,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin34 */
	/* CAN使能 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_11,
		.m_PinNum = GPIO_Pin_Num_11,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 1u,
	},

	/* pin35 */
	/* 预留 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_12,
		.m_PinNum = GPIO_Pin_Num_12,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin36 */
	/* 预留 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_13,
		.m_PinNum = GPIO_Pin_Num_13,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin39 */
	/* 主驾加热NTC采集（AD检）【NTC1】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_4,
		.m_PinNum = GPIO_Pin_Num_4,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin40 */
	/* 预驱2 PWM4输出-先EN功能 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_5,
		.m_PinNum = GPIO_Pin_Num_5,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin41 */
	/* 预留 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin42 */
	/* 主驾坐垫前部角度向前调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_7,
		.m_PinNum = GPIO_Pin_Num_7,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin43 */
	/* 主驾靠背调节电机电流检测（AD检）【低边采集】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin44 */
	/* 主驾高度调节电机电流检测（AD检）【低边采集】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_9,
		.m_PinNum = GPIO_Pin_Num_9,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin45 */
	/* 副驾纵向调节电机电流检测（AD检）预驱1 CS01【高边采集】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_11,
		.m_PinNum = GPIO_Pin_Num_11,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin46 */
	/* 副驾靠背调节电机电流检测（AD检）预驱1 CS02【高边采集】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOA_SFR,
		.m_Pin = GPIO_PIN_MASK_13,
		.m_PinNum = GPIO_Pin_Num_13,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin47 */
	/* 主驾纵向调节电机电流检测（AD检）预驱2 CS01【高边采集】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin48 */
	/* 副驾靠背向后调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin49 */
	/* 主驾高度向下调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin50 */
	/* 副驾靠背向前调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOE_SFR,
		.m_Pin = GPIO_PIN_MASK_3,
		.m_PinNum = GPIO_Pin_Num_3,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin51 */
	/* 主驾高度向上调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin52 */
	/* 主驾纵向向后调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_1,
		.m_PinNum = GPIO_Pin_Num_1,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin53 */
	/* 主驾前部角度调节电机电流检测（AD检）预驱2 CS02【高边采集】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_3,
		.m_PinNum = GPIO_Pin_Num_3,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin54 */
	/* 副驾加热NCT采集（AD检）【NTC2】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_4,
		.m_PinNum = GPIO_Pin_Num_4,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin55 */
	/* NTC3采集（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_7,
		.m_PinNum = GPIO_Pin_Num_7,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin56 */
	/* NTC4采集（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin57 */
	/* 方向盘加热NTC采集（AD检）【NTC5】 */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_11,
		.m_PinNum = GPIO_Pin_Num_11,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin58 */
	/* 板端NTC采集（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin59 */
	/* 预留 */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_10,
		.m_PinNum = GPIO_Pin_Num_10,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin62 */
	/* 主驾加热控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_13,
		.m_PinNum = GPIO_Pin_Num_13,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin63 */
	/* 副驾加热控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_14,
		.m_PinNum = GPIO_Pin_Num_14,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin64 */
	/* 主驾加热电流反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOB_SFR,
		.m_Pin = GPIO_PIN_MASK_15,
		.m_PinNum = GPIO_Pin_Num_15,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin65 */
	/* 副驾加热电流反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin66 */
	/* 霍尔供电反馈（预留）（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_1,
		.m_PinNum = GPIO_Pin_Num_1,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin67 */
	/* 主驾纵向向前调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin68 */
	/* KL30检测 */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_3,
		.m_PinNum = GPIO_Pin_Num_3,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin69 */
	/* 加热3控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_5,
		.m_PinNum = GPIO_Pin_Num_5,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin70 */
	/* 加热3&4电流检测（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin71 */
	/* 加热3&4电流检测切换 */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin72 */
	/* 加热4控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_10,
		.m_PinNum = GPIO_Pin_Num_10,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin73 */
	/* 方向盘加热电流反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_12,
		.m_PinNum = GPIO_Pin_Num_12,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin74 */
	/* 方向盘加热控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_14,
		.m_PinNum = GPIO_Pin_Num_14,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin75 */
	/* EEPROM（I2C） */
	{
		.pinEnable     = TRUE,
		.base = GPIOF_SFR,
		.m_Pin = GPIO_PIN_MASK_15,
		.m_PinNum = GPIO_Pin_Num_15,
		.m_OpenDrain = GPIO_POD_OD,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT5,
		.initValue = 0u,
	},

	/* pin76 */
	/* EEPROM（I2C） */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_OD,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT5,
		.initValue = 0u,
	},

	/* pin77 */
	/* 副驾纵向向后调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin78 */
	/* 副驾纵向向前调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_4,
		.m_PinNum = GPIO_Pin_Num_4,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin79 */
	/* 主驾靠背角度向后调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin80 */
	/* 主驾靠背角度向前调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_2,
		.m_PinNum = GPIO_Pin_Num_2,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin81 */
	/* 主驾坐垫前部角度向后调节开关检测（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_9,
		.m_PinNum = GPIO_Pin_Num_9,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin82 */
	/* 主驾通风PWM输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_10,
		.m_PinNum = GPIO_Pin_Num_10,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin83 */
	/* 副驾通风PWM输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_11,
		.m_PinNum = GPIO_Pin_Num_11,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin84 */
	/* 通风3 PWM输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_12,
		.m_PinNum = GPIO_Pin_Num_12,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin85 */
	/* 通风4 PWM输出 */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_13,
		.m_PinNum = GPIO_Pin_Num_13,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_RMP,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT2,
		.initValue = 0u,
	},

	/* pin88 */
	/* KL15检测（高低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_5,
		.m_PinNum = GPIO_Pin_Num_5,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin89 */
	/* 记忆开关检测（预留）（低检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_6,
		.m_PinNum = GPIO_Pin_Num_6,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin90 */
	/* 主驾纵向霍尔反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_10,
		.m_PinNum = GPIO_Pin_Num_10,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_HIGH_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin91 */
	/* 主驾高度霍尔反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_11,
		.m_PinNum = GPIO_Pin_Num_11,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin92 */
	/* 主驾靠背霍尔反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_12,
		.m_PinNum = GPIO_Pin_Num_12,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin93 */
	/* 主驾坐垫前部角度霍尔反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_13,
		.m_PinNum = GPIO_Pin_Num_13,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin94 */
	/* 副驾纵向霍尔反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_14,
		.m_PinNum = GPIO_Pin_Num_14,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin95 */
	/* 副驾靠背霍尔反馈（AD检） */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_8,
		.m_PinNum = GPIO_Pin_Num_8,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_AN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin96 */
	/* 烧录口 */
	{
		.pinEnable     = FALSE,
		.base = GPIOC_SFR,
		.m_Pin = GPIO_PIN_MASK_15,
		.m_PinNum = GPIO_Pin_Num_15,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin97 */
	/* 复位 */
	{
		.pinEnable     = FALSE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_0,
		.m_PinNum = GPIO_Pin_Num_0,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin98 */
	/* 烧录口 */
	{
		.pinEnable     = FALSE,
		.base = GPIOD_SFR,
		.m_Pin = GPIO_PIN_MASK_1,
		.m_PinNum = GPIO_Pin_Num_1,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_NOPULL,
		.m_Mode = GPIO_MODE_IN,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin99 */
	/* 霍尔供电控制（预留） */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_14,
		.m_PinNum = GPIO_Pin_Num_14,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 0u,
	},

	/* pin100 */
	/* CAN STB控制 */
	{
		.pinEnable     = TRUE,
		.base = GPIOG_SFR,
		.m_Pin = GPIO_PIN_MASK_15,
		.m_PinNum = GPIO_Pin_Num_15,
		.m_OpenDrain = GPIO_POD_PP,
		.m_PullDown = GPIO_NOPULL,
		.m_PullUp = GPIO_PULLUP,
		.m_Mode = GPIO_MODE_OUT,
		.m_Speed = GPIO_LOW_SPEED,
		.mux = PORT_MUX_ALT0,
		.initValue = 1u,
	},

};
